name: Deploy gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      
      -
        name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v1
        with:
          pages_threshold: major_outage
      -
        name: Deploy
        if: success()
        uses: ./
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
